import math
import tkinter as tk

# ============================================================
# ESCAPE ROOM CG - ROOM 1
# DDA + MIDPOINT CIRCLE + 2D TRANSLATION
# ============================================================

WIDTH = 858
HEIGHT = 700
PIXEL = 2

BG = "#050607"
WHITE = "#E8E8E8"
LIGHT_GREY = "#87898A"
GRID = "#111516"
DARK_GREY = "#252829"
YELLOW = "#E7C52F"
GREEN = "#50D876"
RED = "#F0443E"

# ---------------------------
# Player / movement settings
# ---------------------------

MOVE_STEP = 3.0

# Smaller value = more frequent movement updates.
MOVEMENT_INTERVAL = 8

PLAYER_SIZE = 8
PLAYER_COLOR = GREEN

PLAYER_MIN_X = 30
PLAYER_MAX_X = 395
PLAYER_MIN_Y = 50
PLAYER_MAX_Y = 290

# Player's position in logical CG coordinates.
player_x = 110.0
player_y = 270.0

# Keys that are currently being held.
keys_held = set()

# Canvas tag used only for the player.
PLAYER_TAG = "player"

# Room coordinate system.
ROOM_L, ROOM_R = 22, 405
ROOM_T, ROOM_B = 40, 306


# ============================================================
# TKINTER SETUP
# ============================================================

root = tk.Tk()
root.title(
    "Escape Room - Room 1 | DDA + Midpoint Circle + Translation"
)

canvas = tk.Canvas(
    root,
    width=WIDTH,
    height=HEIGHT,
    bg=BG,
    highlightthickness=0,
)

canvas.pack()


# ============================================================
# PIXEL PLOTTER
# ============================================================

def plot(x, y, color=WHITE, tag="world"):
    """
    Plot one logical pixel.

    Tkinter is only being used to display the individual
    pixels generated by our algorithms.
    """

    x = int(round(x))
    y = int(round(y))

    canvas.create_rectangle(
        x * PIXEL,
        y * PIXEL,
        x * PIXEL + PIXEL,
        y * PIXEL + PIXEL,
        fill=color,
        outline=color,
        tags=tag,
    )


# ============================================================
# DDA LINE DRAWING ALGORITHM
# ============================================================

def dda(x1, y1, x2, y2, color=WHITE, tag="world"):
    """
    Digital Differential Analyzer (DDA) line algorithm.
    """

    dx = x2 - x1
    dy = y2 - y1

    steps = max(abs(dx), abs(dy))

    if steps == 0:
        plot(x1, y1, color, tag)
        return

    x_inc = dx / steps
    y_inc = dy / steps

    x = x1
    y = y1

    # int(round(...)) is important because transformations
    # can produce floating-point coordinates.
    for _ in range(int(round(steps)) + 1):
        plot(x, y, color, tag)

        x += x_inc
        y += y_inc


# ============================================================
# MIDPOINT CIRCLE DRAWING ALGORITHM
# ============================================================

def midpoint_circle(cx, cy, radius, color=WHITE, tag="world"):
    """
    Midpoint Circle Drawing Algorithm using 8-way symmetry.
    """

    x = 0
    y = radius

    # Initial decision parameter.
    p = 1 - radius

    def plot_symmetric_points(px, py):
        points = (
            (cx + px, cy + py),
            (cx - px, cy + py),
            (cx + px, cy - py),
            (cx - px, cy - py),

            (cx + py, cy + px),
            (cx - py, cy + px),
            (cx + py, cy - px),
            (cx - py, cy - px),
        )

        for qx, qy in points:
            plot(qx, qy, color, tag)

    plot_symmetric_points(x, y)

    while x < y:

        x += 1

        if p < 0:
            p += 2 * x + 1

        else:
            y -= 1
            p += 2 * (x - y) + 1

        plot_symmetric_points(x, y)


def filled_circle(cx, cy, radius, color, tag="world"):
    """
    Filled-looking circle constructed using concentric
    Midpoint Circle outlines.
    """

    for r in range(radius, 0, -1):
        midpoint_circle(cx, cy, r, color, tag)


# ============================================================
# BASIC SHAPES
# ============================================================

def rect(x, y, w, h, color=WHITE, tag="world"):
    """
    Rectangle constructed using four DDA lines.
    """

    dda(x, y, x + w, y, color, tag)
    dda(x + w, y, x + w, y + h, color, tag)
    dda(x + w, y + h, x, y + h, color, tag)
    dda(x, y + h, x, y, color, tag)


def draw_text(
    x,
    y,
    value,
    color=WHITE,
    size=8,
    bold=False,
    tag="ui",
):
    """
    Text is rendered separately because text itself is not
    part of the line/circle drawing algorithms.
    """

    canvas.create_text(
        x * PIXEL,
        y * PIXEL,
        text=value,
        fill=color,
        anchor="center",
        font=(
            "Consolas",
            size,
            "bold" if bold else "normal",
        ),
        tags=tag,
    )


# ============================================================
# TITLE
# ============================================================

def draw_title():

    draw_text(
        214,
        17,
        "ROOM 1  -  RECEPTION",
        WHITE,
        12,
        True,
    )

    draw_text(
        214,
        30,
        "(DRAWN USING DDA + MIDPOINT CIRCLE)",
        GREEN,
        7,
        True,
    )


# ============================================================
# FLOOR GRID
# ============================================================

def draw_grid():

    # Vertical grid lines.
    for x in range(28, 401, 10):

        dda(
            x,
            ROOM_T + 7,
            x,
            ROOM_B - 7,
            GRID,
        )

    # Horizontal grid lines.
    for y in range(47, ROOM_B, 10):

        dda(
            ROOM_L + 7,
            y,
            ROOM_R - 7,
            y,
            GRID,
        )


# ============================================================
# ARCHITECTURAL WALLS
# ============================================================

def corner_block(x, y, size=14):

    rect(
        x,
        y,
        size,
        size,
        WHITE,
    )

    dda(
        x,
        y,
        x + size,
        y + size,
        DARK_GREY,
    )

    dda(
        x + size,
        y,
        x,
        y + size,
        DARK_GREY,
    )


def draw_walls():

    # --------------------------------------------------------
    # Outer wall
    # --------------------------------------------------------

    dda(
        ROOM_L,
        ROOM_T,
        ROOM_R,
        ROOM_T,
    )

    dda(
        ROOM_R,
        ROOM_T,
        ROOM_R,
        ROOM_B,
    )

    dda(
        ROOM_R,
        ROOM_B,
        ROOM_L,
        ROOM_B,
    )

    dda(
        ROOM_L,
        ROOM_B,
        ROOM_L,
        ROOM_T,
    )

    # --------------------------------------------------------
    # Inner wall
    # --------------------------------------------------------

    dda(
        ROOM_L + 5,
        ROOM_T + 5,
        ROOM_R - 5,
        ROOM_T + 5,
        LIGHT_GREY,
    )

    dda(
        ROOM_R - 5,
        ROOM_T + 5,
        ROOM_R - 5,
        ROOM_B - 5,
        LIGHT_GREY,
    )

    dda(
        ROOM_R - 5,
        ROOM_B - 5,
        ROOM_L + 5,
        ROOM_B - 5,
        LIGHT_GREY,
    )

    dda(
        ROOM_L + 5,
        ROOM_B - 5,
        ROOM_L + 5,
        ROOM_T + 5,
        LIGHT_GREY,
    )

    # --------------------------------------------------------
    # Corner blocks
    # --------------------------------------------------------

    corner_block(
        ROOM_L,
        ROOM_T,
    )

    corner_block(
        ROOM_R - 14,
        ROOM_T,
    )

    corner_block(
        ROOM_L,
        ROOM_B - 14,
    )

    corner_block(
        ROOM_R - 14,
        ROOM_B - 14,
    )

    # --------------------------------------------------------
    # Left wall structural blocks
    # --------------------------------------------------------

    for y in (130, 250):

        rect(
            ROOM_L - 2,
            y,
            14,
            20,
        )

    # --------------------------------------------------------
    # Right wall structural blocks
    # --------------------------------------------------------

    for y in (140, 250):

        rect(
            ROOM_R - 12,
            y,
            14,
            20,
        )

    # --------------------------------------------------------
    # Top wall segments
    # --------------------------------------------------------

    for x1, x2 in (
        (78, 95),
        (305, 325),
        (347, 360),
    ):

        dda(
            x1,
            ROOM_T,
            x1,
            ROOM_T + 10,
        )

        dda(
            x2,
            ROOM_T,
            x2,
            ROOM_T + 10,
        )

    # --------------------------------------------------------
    # Bottom wall
    # Leave central entrance opening.
    # --------------------------------------------------------

    dda(
        ROOM_L,
        ROOM_B - 14,
        164,
        ROOM_B - 14,
    )

    dda(
        ROOM_L,
        ROOM_B - 5,
        164,
        ROOM_B - 5,
    )

    dda(
        239,
        ROOM_B - 14,
        ROOM_R,
        ROOM_B - 14,
    )

    dda(
        239,
        ROOM_B - 5,
        ROOM_R,
        ROOM_B - 5,
    )

    # Entrance joins.
    dda(
        164,
        ROOM_B - 14,
        164,
        ROOM_B,
    )

    dda(
        239,
        ROOM_B - 14,
        239,
        ROOM_B,
    )

    # --------------------------------------------------------
    # Entry tunnel
    # --------------------------------------------------------

    dda(
        168,
        ROOM_B,
        235,
        ROOM_B,
    )

    dda(
        168,
        ROOM_B,
        168,
        ROOM_B + 22,
    )

    dda(
        235,
        ROOM_B,
        235,
        ROOM_B + 22,
    )

    for y in (
        312,
        316,
        320,
        324,
    ):

        dda(
            178,
            y,
            225,
            y,
            LIGHT_GREY,
        )


# ============================================================
# PLANT
# ============================================================

def draw_plant():

    # Pot.
    rect(
        51,
        77,
        14,
        9,
    )

    # Pot rim.
    midpoint_circle(
        58,
        77,
        8,
    )

    # Stem.
    dda(
        58,
        77,
        58,
        64,
    )

    # Leaves.
    midpoint_circle(
        53,
        62,
        5,
    )

    midpoint_circle(
        63,
        60,
        5,
    )

    midpoint_circle(
        58,
        55,
        5,
    )

    # Leaf veins.
    dda(
        53,
        62,
        58,
        55,
    )

    dda(
        63,
        60,
        58,
        55,
    )


# ============================================================
# TOP WALL PANEL
# ============================================================

def draw_top_panel():

    x = 169
    y = 59
    w = 47
    h = 19

    rect(
        x,
        y,
        w,
        h,
    )

    for yy in (
        64,
        68,
        72,
    ):

        dda(
            x + 8,
            yy,
            x + w - 8,
            yy,
            LIGHT_GREY,
        )


# ============================================================
# FILING CABINET
# ============================================================

def draw_cabinet():

    x = 320
    y = 67
    w = 29
    h = 32

    rect(
        x,
        y,
        w,
        h,
    )

    # Drawer divisions.
    dda(
        x,
        y + 10,
        x + w,
        y + 10,
    )

    dda(
        x,
        y + 20,
        x + w,
        y + 20,
    )

    # Handles.
    midpoint_circle(
        x + 14,
        y + 5,
        2,
    )

    midpoint_circle(
        x + 14,
        y + 15,
        2,
    )

    midpoint_circle(
        x + 14,
        y + 25,
        2,
    )


# ============================================================
# COMPUTER MONITOR
# ============================================================

def draw_monitor(x, y):

    rect(
        x,
        y,
        25,
        17,
    )

    # Stand.
    dda(
        x + 10,
        y + 17,
        x + 10,
        y + 22,
    )

    dda(
        x + 5,
        y + 22,
        x + 18,
        y + 22,
    )


# ============================================================
# KEYBOARD
# ============================================================

def draw_keyboard(x, y):

    rect(
        x,
        y,
        16,
        6,
    )

    for xx in (
        x + 3,
        x + 6,
        x + 9,
        x + 12,
    ):

        dda(
            xx,
            y + 2,
            xx,
            y + 4,
            LIGHT_GREY,
        )


# ============================================================
# RECEPTION DESK
# ============================================================

def draw_reception_desk():

    x = 106
    y = 100
    w = 108
    h = 31

    # Main desk.
    rect(
        x,
        y,
        w,
        h,
    )

    # Front panel.
    dda(
        x,
        y + h + 5,
        x + w,
        y + h + 5,
    )

    # Legs.
    dda(
        x + 9,
        y + h,
        x + 9,
        y + h + 11,
    )

    dda(
        x + w - 9,
        y + h,
        x + w - 9,
        y + h + 11,
    )

    # Monitor.
    draw_monitor(
        126,
        81,
    )

    # Keyboard.
    draw_keyboard(
        160,
        108,
    )

    # Desk accessory.
    rect(
        195,
        109,
        8,
        10,
    )

    midpoint_circle(
        199,
        114,
        2,
    )

    # Label.
    draw_text(
        160,
        145,
        "RECEPTION DESK",
        YELLOW,
        6,
        True,
    )


# ============================================================
# NOTICE BOARD
# ============================================================

def draw_notice_board():

    x = 40
    y = 151
    w = 40
    h = 74

    rect(
        x,
        y,
        w,
        h,
    )

    # Screws.
    for px, py in (
        (x + 5, y + 5),
        (x + w - 5, y + 5),
        (x + 5, y + h - 5),
        (x + w - 5, y + h - 5),
    ):

        midpoint_circle(
            px,
            py,
            2,
        )

    draw_text(
        60,
        194,
        "NOTICE",
        YELLOW,
        6,
        True,
    )

    draw_text(
        60,
        204,
        "BOARD",
        YELLOW,
        6,
        True,
    )


# ============================================================
# TABLE
# ============================================================

def draw_table():

    x = 120
    y = 186
    w = 120
    h = 44

    rect(
        x,
        y,
        w,
        h,
    )

    # Apron.
    dda(
        x + 7,
        y + h + 5,
        x + w - 7,
        y + h + 5,
    )

    # Legs.
    dda(
        x + 10,
        y + h,
        x + 10,
        y + h + 10,
    )

    dda(
        x + w - 10,
        y + h,
        x + w - 10,
        y + h + 10,
    )

    draw_text(
        180,
        244,
        "TABLE",
        YELLOW,
        6,
        True,
    )


# ============================================================
# STORAGE CRATE
# ============================================================

def draw_storage_crate():

    x = 305
    y = 190
    s = 30

    rect(
        x,
        y,
        s,
        s,
    )

    # Inner frame.
    rect(
        x + 3,
        y + 3,
        s - 6,
        s - 6,
        LIGHT_GREY,
    )

    # Cross braces.
    dda(
        x + 3,
        y + 3,
        x + s - 3,
        y + s - 3,
    )

    dda(
        x + s - 3,
        y + 3,
        x + 3,
        y + s - 3,
    )

    draw_text(
        320,
        226,
        "STORAGE",
        YELLOW,
        6,
        True,
    )

    draw_text(
        320,
        236,
        "CRATE",
        YELLOW,
        6,
        True,
    )


# ============================================================
# LOCKED DOOR
# ============================================================

def draw_locked_door():

    x = 365
    y = 176
    w = 31
    h = 84

    # Door.
    rect(
        x,
        y,
        w,
        h,
    )

    # Inner panel.
    rect(
        x + 4,
        y + 4,
        w - 8,
        h - 8,
        LIGHT_GREY,
    )

    # Handle.
    midpoint_circle(
        x + 8,
        y + 42,
        2,
    )

    # Keypad.
    rect(
        x + 38,
        y + 23,
        7,
        15,
    )

    # Red indicator.
    filled_circle(
        x + 41,
        y + 31,
        2,
        RED,
    )

    draw_text(
        337,
        252,
        "LOCKED DOOR",
        RED,
        6,
        True,
    )

    draw_text(
        322,
        262,
        "(NEED ACCESS CARD)",
        RED,
        5,
    )


# ============================================================
# ENTRY POINT
# ============================================================

def draw_entry():

    # Entry indicator.
    rect(
        195,
        296,
        18,
        3,
        GREEN,
    )

    filled_circle(
        204,
        297,
        2,
        GREEN,
    )

    # Entry steps.
    for y in (
        312,
        316,
        320,
        324,
    ):

        dda(
            178,
            y,
            225,
            y,
            LIGHT_GREY,
        )

    draw_text(
        204,
        336,
        "ENTRY POINT",
        GREEN,
        6,
        True,
    )


# ============================================================
# COMPLETE ROOM
# ============================================================

def draw_room():

    draw_walls()

    draw_plant()

    draw_top_panel()

    draw_cabinet()

    draw_reception_desk()

    draw_notice_board()

    draw_table()

    draw_storage_crate()

    draw_locked_door()

    draw_entry()


# ============================================================
# TRANSFORMATION STATE
# ============================================================

# Current player transformation values.
player_angle = 0.0
player_scale = 1.0


# ============================================================
# PLAYER DRAWING
# ============================================================

def player_pixel(x, y, color=PLAYER_COLOR):

    plot(
        x,
        y,
        color,
        PLAYER_TAG,
    )


def player_line(
    x1,
    y1,
    x2,
    y2,
    color=PLAYER_COLOR,
):
    """
    DDA-based line specifically for the dynamic player layer.
    """

    dx = x2 - x1
    dy = y2 - y1

    steps = max(abs(dx), abs(dy))

    if steps == 0:
        player_pixel(
            x1,
            y1,
            color,
        )
        return

    x_inc = dx / steps
    y_inc = dy / steps

    x = x1
    y = y1

    # IMPORTANT:
    # The iteration count must be integer because smooth
    # diagonal translation produces floating-point coordinates.
    for _ in range(int(round(steps)) + 1):

        player_pixel(
            x,
            y,
            color,
        )

        x += x_inc
        y += y_inc


def player_circle(
    cx,
    cy,
    radius,
    color=PLAYER_COLOR,
):
    """
    Midpoint-circle style rendering for player detail.
    """

    x = 0
    y = radius
    p = 1 - radius

    def emit(px, py):

        points = (
            (cx + px, cy + py),
            (cx - px, cy + py),
            (cx + px, cy - py),
            (cx - px, cy - py),

            (cx + py, cy + px),
            (cx - py, cy + px),
            (cx + py, cy - px),
            (cx - py, cy - px),
        )

        for qx, qy in points:

            player_pixel(
                qx,
                qy,
                color,
            )

    emit(x, y)

    while x < y:

        x += 1

        if p < 0:

            p += 2 * x + 1

        else:

            y -= 1
            p += 2 * (x - y) + 1

        emit(x, y)


def scaling_matrix(sx, sy):
    """
    Homogeneous 2D scaling matrix:

        [ sx  0   0 ]
    S = [  0 sy   0 ]
        [  0  0   1 ]
    """
    return [
        [sx, 0, 0],
        [0, sy, 0],
        [0, 0, 1],
    ]


def rotation_matrix(angle_degrees):
    """
    Homogeneous 2D rotation matrix about the origin:

        [ cos -sin  0 ]
    R = [ sin  cos  0 ]
        [  0    0   1 ]
    """
    theta = math.radians(angle_degrees)
    c = math.cos(theta)
    s = math.sin(theta)

    return [
        [c, -s, 0],
        [s,  c, 0],
        [0,  0, 1],
    ]


def multiply_matrices(A, B):
    """Multiply two 3x3 homogeneous matrices."""
    return [
        [
            sum(A[i][k] * B[k][j] for k in range(3))
            for j in range(3)
        ]
        for i in range(3)
    ]


def apply_matrix(x, y, M):
    """Apply a 3x3 homogeneous matrix to a 2D point."""
    return (
        M[0][0] * x + M[0][1] * y + M[0][2],
        M[1][0] * x + M[1][1] * y + M[1][2],
    )


def transform_local_point(local_x, local_y, scale=1.0, angle_degrees=0.0):
    """
    Apply scaling first and rotation second to the player's
    local coordinates, then translate the result to the player's
    current world position.
    """
    S = scaling_matrix(scale, scale)
    R = rotation_matrix(angle_degrees)

    # Composite transformation: R * S
    M = multiply_matrices(R, S)

    x, y = apply_matrix(local_x, local_y, M)

    # Translation is the player's current position.
    return player_x + x, player_y + y


def draw_transformed_player_shape():
    """
    Draw the player from local coordinates.

    The same local shape is scaled and rotated before being
    translated to the player's current position.
    """

    local_points = [
        (0, -5),
        (4, 0),
        (2, 4),
        (0, 2),
        (-3, 5),
        (-4, 0),
    ]

    points = [
        transform_local_point(
            x,
            y,
            player_scale,
            player_angle,
        )
        for x, y in local_points
    ]

    # Draw transformed polygon edges using DDA.
    for i in range(len(points)):
        x1, y1 = points[i]
        x2, y2 = points[(i + 1) % len(points)]

        player_line(
            x1,
            y1,
            x2,
            y2,
        )

    # Circular detail also follows scaling.
    hx, hy = transform_local_point(
        0,
        -3,
        player_scale,
        player_angle,
    )

    radius = max(
        1,
        int(round(2 * player_scale)),
    )

    player_circle(
        int(round(hx)),
        int(round(hy)),
        radius,
    )


def draw_player():
    """
    Redraw only the transformed player.
    """

    canvas.delete(
        PLAYER_TAG
    )

    draw_transformed_player_shape()


# ============================================================
# SCALING AND ROTATION CONTROLS
# ============================================================

def rotate_player(delta):
    """Rotate the player around its own center."""
    global player_angle

    player_angle = (
        player_angle + delta
    ) % 360

    draw_player()


def scale_player(factor):
    """Scale the player uniformly while keeping a safe range."""
    global player_scale

    player_scale *= factor

    # Keep the player reasonably visible.
    player_scale = max(
        0.5,
        min(2.0, player_scale),
    )

    draw_player()


# ============================================================
# COLLISION
# ============================================================

def player_collides(x, y):

    half = PLAYER_SIZE / 2

    left = x - half
    right = x + half

    top = y - half
    bottom = y + half

    # Current Room 1 obstacles.
    obstacles = [

        # Reception desk.
        (106, 100, 108, 31),

        # Table.
        (120, 186, 120, 44),

        # Storage crate.
        (305, 190, 30, 30),

        # Filing cabinet.
        (320, 67, 29, 32),

        # Notice board.
        (40, 151, 40, 74),
    ]

    for ox, oy, ow, oh in obstacles:

        if (
            right > ox
            and left < ox + ow
            and bottom > oy
            and top < oy + oh
        ):
            return True

    return False


# ============================================================
# TRANSLATION MATRIX
# ============================================================

def translation_matrix(tx, ty):
    """
    Homogeneous 2D translation matrix:

        [ 1   0   tx ]
    T = [ 0   1   ty ]
        [ 0   0    1 ]
    """

    return [
        [1, 0, tx],
        [0, 1, ty],
        [0, 0, 1],
    ]


def translate_point(x, y, tx, ty):
    """
    Apply the translation:

        P' = T * P
    """

    T = translation_matrix(
        tx,
        ty,
    )

    new_x = (
        T[0][0] * x
        + T[0][1] * y
        + T[0][2]
    )

    new_y = (
        T[1][0] * x
        + T[1][1] * y
        + T[1][2]
    )

    return new_x, new_y


# ============================================================
# PLAYER MOVEMENT
# ============================================================

def move_player(dx, dy):

    global player_x
    global player_y

    # Apply 2D translation.
    new_x, new_y = translate_point(
        player_x,
        player_y,
        dx,
        dy,
    )

    # Keep the player inside the room.
    new_x = max(
        PLAYER_MIN_X,
        min(
            PLAYER_MAX_X,
            new_x,
        )
    )

    new_y = max(
        PLAYER_MIN_Y,
        min(
            PLAYER_MAX_Y,
            new_y,
        )
    )

    # Commit translation only if there is no collision.
    if not player_collides(
        new_x,
        new_y,
    ):

        player_x = new_x
        player_y = new_y

        # Only redraw the player.
        draw_player()


# ============================================================
# KEYBOARD
# ============================================================

def key_down(event):

    key = event.keysym.lower()

    movement_keys = {
        "w",
        "a",
        "s",
        "d",
        "up",
        "down",
        "left",
        "right",
    }

    if key in movement_keys:

        keys_held.add(key)
        return

    # --------------------------------------------------------
    # Transformation controls
    # Q / E : rotate player
    # Z / X : scale player down / up
    # --------------------------------------------------------

    if key == "q":
        rotate_player(-5)

    elif key == "e":
        rotate_player(5)

    elif key == "z":
        scale_player(0.95)

    elif key == "x":
        scale_player(1.05)


def key_up(event):

    key = event.keysym.lower()

    # As soon as the key is released it is removed.
    # The next movement cycle therefore produces no movement
    # for that key.
    keys_held.discard(key)


root.bind(
    "<KeyPress>",
    key_down,
)

root.bind(
    "<KeyRelease>",
    key_up,
)


# ============================================================
# SMOOTH MOVEMENT LOOP
# ==================    ==========================================

def smooth_movement():
    """
    Continuous press-and-hold movement.

    Key pressed + held:
        player keeps translating.

    Key released:
        that direction immediately becomes zero.
    """

    dx = 0.0
    dy = 0.0

    # Up.
    if (
        "w" in keys_held
        or "up" in keys_held
    ):
        dy -= MOVE_STEP

    # Down.
    if (
        "s" in keys_held
        or "down" in keys_held
    ):
        dy += MOVE_STEP

    # Left.
    if (
        "a" in keys_held
        or "left" in keys_held
    ):
        dx -= MOVE_STEP

    # Right.
    if (
        "d" in keys_held
        or "right" in keys_held
    ):
        dx += MOVE_STEP

    # Prevent diagonal movement from being faster.
    if dx != 0 and dy != 0:

        dx *= 0.70710678
        dy *= 0.70710678

    # If no movement key is held:
    # dx = 0 and dy = 0, so the player stops.
    if dx != 0 or dy != 0:

        move_player(
            dx,
            dy,
        )

    # Schedule the next movement check.
    root.after(
        MOVEMENT_INTERVAL,
        smooth_movement,
    )


# ============================================================
# STATIC SCENE
# ============================================================

def draw_static_scene():

    canvas.delete(
        "world"
    )

    canvas.delete(
        "ui"
    )

    draw_grid()
    draw_title()
    draw_room()

    draw_text(
        214,
        345,
        "W/A/S/D = TRANSLATION   Q/E = ROTATION   Z/X = SCALING",
        GREEN,
        6,
        True,
    )

    draw_text(
        214,
        357,
        f"ANGLE: {player_angle:.0f} deg    SCALE: {player_scale:.2f}x",
        YELLOW,
        6,
        True,
    )


# ============================================================
# START
# ============================================================

print(
    "Escape Room Room 1"
)

print(
    "DDA + Midpoint Circle + Translation + Scaling + Rotation"
)

print(
    "W/A/S/D or Arrow Keys = Move / Translation"
)

print(
    "Q/E = Rotate | Z/X = Scale"
)

print(
    "Hold key = move continuously | Release = stop"
)

# Draw the room only once.
draw_static_scene()

# Draw player once initially.
draw_player()

# Start the continuous movement loop.
smooth_movement()

root.mainloop() 